### ISSUE TITLE
Can't run a project using cli

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/OpenStudio-analysis-spreadsheet#18]
I am trying to run a project outside of the OpenStudio-analysis-spreadsheet repo using the CLI, however I get this error:

cli.rb:43:in `process_excel_project': undefined method`aws_instance_options' for OpenStudio::Analysis:Module (NoMethodError)
        from cli.rb:417:in `<main>'

**Comment by rHorsey** [comment]
This is due to the Gemfile not pointing towards the latest state of the OpenStudio-Analysis-Gem. The gem will be re-released shortly on rubygems and subsequently updated in the Gemfile in this repo, however until then please uncomment line 13 and comment out line 12 of https://github.com/NREL/OpenStudio-analysis-spreadsheet/blob/develop/Gemfile. This issue will be closed when the new release is set as the default in develop of this repo.

**Comment by rHorsey** [comment]
Also fixed.
